### ISSUE TITLE
update the deps to latest levels

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/powervs-csi-driver#6]
Update the below dependencies to expected versions to avoid security issues:

- k8s.io/kubernetes v1.22.3
- Golang-jwt v3.2.1

**Comment by Madhan-SWE** [comment]
Upgrading k8s.io/kubernetes v1.22.3 creates below issue.

```
go: downloading k8s.io/kubernetes v1.22.3
go get: k8s.io/kubernetes@v1.22.3 requires
	k8s.io/component-helpers@v0.0.0: reading k8s.io/component-helpers/go.mod at revision v0.0.0: unknown revision
```

**Comment by Madhan-SWE** [comment]
No patch available to solve vulnerabilities in Golang-jwt package.
Dependabot is suggesting to use version 3.2.1.

But, unable to upgrade to version 3.2.1
```
[root@madhan-multinode-kube-master powervs-csi-driver]# go get github.com/dgrijalva/jwt-go@v3.2.1
go get github.com/dgrijalva/jwt-go@v3.2.1: github.com/dgrijalva/jwt-go@v3.2.1: invalid version: unknown revision v3.2.1
```

Even updating the Golang-jwt package to the latest version shows the current version and updated version as same vulnerable version.

```
[root@madhan-multinode-kube-master powervs-csi-driver]# go get github.com/dgrijalva/jwt-go
[root@madhan-multinode-kube-master powervs-csi-driver]# go list -m all | grep jwt
github.com/auth0/go-jwt-middleware v0.0.0-20170425171159-5493cabe49f7
github.com/dgrijalva/jwt-go v3.2.0+incompatible
[root@madhan-multinode-kube-master powervs-csi-driver]#
```

**Comment by Madhan-SWE** [comment]
@Karthik-K-N any thoughts on this?

**Comment by Karthik-K-N** [comment]
Did you try this` go mod edit -require=k8s.io/kubernetes@v1.22.3 then go mod tidy`

**Comment by mkumatag** [comment]
> No patch available to solve vulnerabilities in Golang-jwt package.
> Dependabot is suggesting to use version 3.2.1.
> 
> But, unable to upgrade to version 3.2.1
> ```
> [root@madhan-multinode-kube-master powervs-csi-driver]# go get github.com/dgrijalva/jwt-go@v3.2.1
> go get github.com/dgrijalva/jwt-go@v3.2.1: github.com/dgrijalva/jwt-go@v3.2.1: invalid version: unknown revision v3.2.1
> ```
> 
> Even updating the Golang-jwt package to the latest version shows the current version and updated version as same vulnerable version.
> 
> ```
> [root@madhan-multinode-kube-master powervs-csi-driver]# go get github.com/dgrijalva/jwt-go
> [root@madhan-multinode-kube-master powervs-csi-driver]# go list -m all | grep jwt
> github.com/auth0/go-jwt-middleware v0.0.0-20170425171159-5493cabe49f7
> github.com/dgrijalva/jwt-go v3.2.0+incompatible
> [root@madhan-multinode-kube-master powervs-csi-driver]#
> ```

Can you try using: `github.com/golang-jwt/jwt` instead..

**Comment by Madhan-SWE** [comment]
> Did you try this` go mod edit -require=k8s.io/kubernetes@v1.22.3 then go mod tidy`

fails with same error

```
[root@madhan-multinode-kube-master powervs-csi-driver]# go mod edit -require=k8s.io/kubernetes@v1.22.3
[root@madhan-multinode-kube-master powervs-csi-driver]# go mod tidy
go: k8s.io/kubernetes@v1.22.3 requires
	k8s.io/component-helpers@v0.0.0: reading k8s.io/component-helpers/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by Karthik-K-N** [comment]
then give shot with earlier version like k8s.io/kubernetes@v1.22

**Comment by Madhan-SWE** [comment]
> > No patch available to solve vulnerabilities in Golang-jwt package.
> > Dependabot is suggesting to use version 3.2.1.
> > But, unable to upgrade to version 3.2.1
> > ```
> > [root@madhan-multinode-kube-master powervs-csi-driver]# go get github.com/dgrijalva/jwt-go@v3.2.1
> > go get github.com/dgrijalva/jwt-go@v3.2.1: github.com/dgrijalva/jwt-go@v3.2.1: invalid version: unknown revision v3.2.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Even updating the Golang-jwt package to the latest version shows the current version and updated version as same vulnerable version.
> > ```
> > [root@madhan-multinode-kube-master powervs-csi-driver]# go get github.com/dgrijalva/jwt-go
> > [root@madhan-multinode-kube-master powervs-csi-driver]# go list -m all | grep jwt
> > github.com/auth0/go-jwt-middleware v0.0.0-20170425171159-5493cabe49f7
> > github.com/dgrijalva/jwt-go v3.2.0+incompatible
> > [root@madhan-multinode-kube-master powervs-csi-driver]#
> > ```
> 
> Can you try using: `github.com/golang-jwt/jwt` instead..


Changing from github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt solves the issue.

**Comment by Madhan-SWE** [comment]
> then give shot with earlier version like k8s.io/kubernetes

The current version is 1.19.14. I can upgrade to any of the 1.19.x version. But, I can't upgrade to 1.20.0 or more than that.

**Comment by Madhan-SWE** [comment]
I am using Kubernetes cluster version 1.19.2. I think that's why I cannot install client beyond 1.19.x.
I will create a single node cluster with latest Kubernetes version and test there.

**Comment by Madhan-SWE** [comment]
Deployed new Kubernetes cluster version 1.22.2.
Tried to upgrade the kubernetes package to v1.22.3.
Still getting the same error
```
[root@madhan-1-kube-1-22-2 powervs-csi-driver]# go get k8s.io/kubernetes@v1.22.3 requires
go: k8s.io/kubernetes@v1.22.3 requires
	k8s.io/component-helpers@v0.0.0: reading k8s.io/component-helpers/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by mkumatag** [comment]
best way to fix them via replace directive in the go.mod file, e.g: https://github.com/kubernetes-csi/csi-driver-nfs/blob/96d13a56e5974310618f0064e5026211a23dd340/go.mod#L25:L52

**Comment by Madhan-SWE** [comment]
> best way to fix them via replace directive in the go.mod file, e.g: https://github.com/kubernetes-csi/csi-driver-nfs/blob/96d13a56e5974310618f0064e5026211a23dd340/go.mod#L25:L52

fixes the issue. Thanks

**Comment by Madhan-SWE** [comment]
Updating the dependencies to the latest version requires the go version 1.16 to build and test.
Working on go installation.
